name: Build DocFX

on:
    push:
        branches:
            - 'test-actions'
        tags:
            - '*.*.*'

jobs:
    build:

        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup .NET versions
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: |
                      3.1.x
                      6.0.x

            - name: Clone dark theme
              uses: actions/checkout@v3
              with:
                  repository: steffen-wilke/darkfx
                  persist-credentials: false
                  path: docs/templates/darkfx

            - name: Install docfx
              uses: crazy-max/ghaction-chocolatey@v2
              with:
                  args: install docfx

            - name: Build .NET Core
              run: dotnet build --configuration Release

            - name: Run docFX
              run: |
                  docfx docs/docfx.json -t default,templates/darkfx/darkfx

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: site
                  path: docs/dist/

    deploy:

        needs: [ build ]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Download Artifacts
              uses: actions/download-artifact@v3
              with:
                  name: site

            - name: Install SSH Client
              uses: webfactory/ssh-agent@v0.5.4
              with:
                  ssh-private-key: ${{ secrets.DEPLOY_KEY_WRITE }}

            - name: Deploy to GitHub pages
              uses: JamesIves/github-pages-deploy-action@releases/v4
              with:
                  ssh-key: true
                  branch: gh-pages
                  folder: "site"
                  clean: true
